### ISSUE TITLE
bump to @quirrel/client v0.6.2

### ISSUE THREAD

**Issue by shc023** [quirrel-dev/quirrel-next#1]
Looks like a crashing bug was fixed in `enqueue` recently (`JSON.parse` called twice). Please bump to 0.6.2, thanks! :)

**Comment by Skn0tt** [comment]
Thanks for the heads up ☺️ will get this fixed once I get home.

**Comment by Skn0tt** [comment]
Closed in 9d009b4c954e0f109c8a05983b4e043ec6a248f2, published in [v0.6.1](https://github.com/quirrel-dev/quirrel-next/releases/tag/v0.6.1).
